export const API_URL = "https://wbdv-generic-server.herokuapp.com/api/001059598/courses"
export const DEFAULT_COURSE_TITLE = "New Course"
export const DEFAULT_SECTION_TITLE = "New Section"
export const WIDGET_SERVICE_URL="https://shielded-temple-70812.herokuapp.com"
// export const WIDGET_SERVICE_URL="http://localhost:8080"